name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-v1

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Playwright tests (Chromium only)
        run: npx playwright test --project=chromium

      - name: Publish JUnit Test Results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'test-results/results.xml'
          report-name: 'Playwright Tests'

      - name: Upload HTML Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30
